const fs = require('fs');

const viPath = 'backend/lang/vi.json';
let vi = JSON.parse(fs.readFileSync(viPath, 'utf8'));

const newKeys = {
    "New Production Line": "Dây chuyền sản xuất mới",
    "New Workstation": "Trạm làm việc mới",
    "New Material": "Vật liệu mới",
    "New Product Type": "Loại sản phẩm mới",
    "New Process Template": "Mẫu quy trình mới",
    "New Process Step": "Bước quy trình mới",
    "New Work Order": "Lệnh làm việc mới",
    "Dashboard": "Bảng điều khiển",
    "Product Types": "Loại sản phẩm",
    "Process Templates": "Mẫu quy trình",
    "Work Orders": "Lệnh làm việc",
    "Recent Work Orders": "Lệnh làm việc gần đây",
    "No process templates yet": "Chưa có mẫu quy trình nào",
    "No work orders yet": "Chưa có lệnh làm việc nào",
    "Process templates define how this product is manufactured.": "Các mẫu quy trình xác định cách sản phẩm này được sản xuất.",
    "Back to Templates": "Quay lại Mẫu",
    "Template Name": "Tên mẫu",
    "e.g., Standard Assembly Process, Quality Inspection v2": "VD: Quy trình lắp ráp tiêu chuẩn, Kiểm tra chất lượng v2",
    "Descriptive name for this manufacturing process": "Tên mô tả cho quy trình sản xuất này",
    "Note:": "Lưu ý:",
    "Version number will be assigned automatically. After creating the template, you'll be able to add production steps.": "Số phiên bản sẽ được chỉ định tự động. Sau khi tạo mẫu, bạn sẽ có thể thêm các bước sản xuất.",
    "Active (template is ready for use in work orders)": "Hoạt động (mẫu đã sẵn sàng để sử dụng trong các lệnh làm việc)",
    "Creating…": "Đang tạo…",
    "Create Template": "Tạo mẫu",
    "Process template created successfully. Now add production steps.": "Tạo mẫu quy trình thành công. Bây giờ hãy thêm các bước sản xuất.",
    "Edit Template": "Chỉnh sửa mẫu",
    "+ Add Step": "+ Thêm bước",
    "Production Steps (first to last)": "Các bước sản xuất (từ đầu đến cuối)",
    "No production steps yet": "Chưa có bước sản xuất nào",
    "Add steps to define the manufacturing process for this product.": "Thêm các bước để xác định quy trình sản xuất cho sản phẩm này.",
    "+ Add First Step": "+ Thêm bước đầu tiên",
    "General Reference Photos (0/20)": "Ảnh tham khảo chung (0/20)",
    "Photo (JPEG/PNG/WebP, max 10 MB)": "Ảnh (JPEG/PNG/WebP, tối đa 10 MB)",
    "Caption": "Chú thích",
    "Upload Photo": "Tải ảnh lên",
    "Are you sure you want to delete this step?": "Bạn có chắc chắn muốn xóa bước này không?",
    "Are you sure you want to delete this photo?": "Bạn có chắc chắn muốn xóa ảnh này không?",
    "Process Template Details": "Chi tiết mẫu quy trình",
    
    // Admin Lines Show
    "Assigned Product Types": "Các loại sản phẩm được chỉ định",
    "Product types that can be produced on this line.": "Các loại sản phẩm có thể được sản xuất trên dây chuyền này.",
    "No product types assigned — all types are allowed.": "Không có loại sản phẩm nào được chỉ định — cho phép tất cả các loại.",
    "Change assignment": "Thay đổi phân công",
    "Hide selector": "Ẩn danh sách",
    "No active product types defined yet.": "Chưa có loại sản phẩm đang hoạt động nào được định nghĩa.",
    "Leave all unchecked to allow all product types on this line.": "Để trống tất cả để cho phép tất cả các loại sản phẩm trên dây chuyền này.",
    "Save Assignment": "Lưu phân công",
    "Workstations": "Trạm sản xuất",
    "No workstations configured — line itself acts as a single workstation.": "Chưa định cấu hình trạm làm việc — bản thân dây chuyền đóng vai trò là một trạm làm việc đơn lẻ.",
    "workstation(s) on this line.": "trạm làm việc trên dây chuyền này.",
    "Manage": "Quản lý",
    "virtual (line = workstation)": "ảo (dây chuyền = trạm làm việc)",
    "Queue": "Hàng đợi",
    "Standard work order list with status, batches, priority and actions.": "Danh sách lệnh làm việc tiêu chuẩn với trạng thái, lô, mức độ ưu tiên và hành động.",
    "Workstation": "Trạm làm việc",
    "Flat production table with quantities, Z1/Z2 shift inputs and inline entry.": "Bảng sản xuất phẳng với số lượng, đầu vào ca Z1/Z2 và nhập dữ liệu tại chỗ.",
    "Workstation View": "Giao diện Trạm làm việc",
    "Select a view template that defines which columns operators see in the Workstation view for this line.": "Chọn một mẫu giao diện xác định các cột mà người vận hành nhìn thấy trong giao diện Trạm làm việc cho dây chuyền này.",
    "View Template": "Mẫu giao diện",
    "— Default (no custom columns) —": "— Mặc định (không có cột tùy chỉnh) —",
    "Save": "Lưu",
    "Workstation View Columns": "Cột Giao diện Trạm làm việc",
    "Configure which columns operators see in the Workstation view for this line. Columns with source": "Định cấu hình các cột người vận hành thấy trong giao diện Trạm làm việc. Cột có nguồn",
    "No custom columns configured. Default view will be shown.": "Không có cột tùy chỉnh nào được định cấu hình. Giao diện mặc định sẽ được hiển thị.",
    "Column Label": "Nhãn cột",
    "Data Key": "Khóa dữ liệu",
    "Source": "Nguồn",
    "e.g. Material": "Vd: Vật liệu",
    "e.g. material": "Vd: vat_lieu",
    "+ Add": "+ Thêm",
    "Save View Columns": "Lưu Cột Giao diện",
    "extra_data": "dữ liệu_thêm"
};

Object.assign(vi, newKeys);
fs.writeFileSync(viPath, JSON.stringify(vi, null, 4));
console.log('vi.json updated successfully.');
