<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title inertia>{{ config('app.name', 'OpenMES') }}</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
    {{-- Geist + Geist Mono — the design-system typefaces (see packages/ui tokens) --}}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&family=Geist+Mono:wght@400;500;600&display=swap" rel="stylesheet">
    <script>
        /* Apply dark class before first paint to avoid a flash (mirrors layouts/app.blade.php) */
        (function(){
            if (localStorage.getItem('theme') === 'dark') {
                document.documentElement.classList.add('dark');
            }
        })();
    </script>
    @viteReactRefresh
    {{-- runtime.generated.js first: it publishes window.__OPENMES__, which the
         scripts of installed modules bind against. Generated by openmesRuntime()
         from packages/module/contract.js — do not add its entries by hand. --}}
    @vite(['resources/css/app.css', 'resources/js/runtime.generated.js', 'resources/js/app.jsx'])
    @inertiaHead
</head>
<body class="bg-gray-100 dark:bg-gray-900">
    @inertia
</body>
</html>
