/**
 * Core-side Vite plugin: publishes the shared runtime that installed modules
 * bind against.
 *
 * The file it generates is the mirror image of the module build's globals map,
 * and both come from `contract.js` — so an entry added on one side cannot go
 * missing on the other. Hand-writing this file was the original plan; it meant
 * keeping two 17-entry lists in step by hand, across two repositories, forever.
 *
 * The generated file is written to disk rather than served as a virtual module
 * because Laravel's Vite plugin takes its inputs as real paths, and an entry
 * that only exists in memory never makes it into the manifest Blade reads.
 */

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { CONTRACT, CONTRACT_VERSION, PAGES_GLOBAL, RUNTIME_GLOBAL } from './contract.js';

/** Default location of the generated entry, relative to the Vite root. */
export const RUNTIME_ENTRY = 'resources/js/runtime.generated.js';

/**
 * Turn the contract's flat "specifier → global path" map into the nested object
 * literal the runtime assigns. '__OPENMES__.core.AppLayout' becomes a key
 * `AppLayout` under `core`; the leading global itself is stripped, since that
 * is what we are building.
 */
function nest(bindings) {
    const tree = {};

    for (const [specifier, globalPath] of Object.entries(CONTRACT)) {
        const segments = globalPath.split('.');

        if (segments.shift() !== RUNTIME_GLOBAL) {
            throw new Error(
                `Contract entry "${specifier}" maps to "${globalPath}", which does not start with ${RUNTIME_GLOBAL}.`,
            );
        }

        let node = tree;
        while (segments.length > 1) {
            const key = segments.shift();
            node[key] ??= {};
            node = node[key];
        }

        node[segments[0]] = bindings.get(specifier);
    }

    return tree;
}

/** Render the nested tree as source, with identifiers left unquoted. */
function render(node, indent = '    ') {
    const lines = Object.entries(node).map(([key, value]) => {
        const rendered = typeof value === 'string' ? value : render(value, `${indent}    `);

        return `${indent}${JSON.stringify(key)}: ${rendered},`;
    });

    return `{\n${lines.join('\n')}\n${indent.slice(4)}}`;
}

function generate() {
    const bindings = new Map();
    const imports = [];

    // Namespace imports throughout: a module's `import X from '…'` reads
    // `.default` off the namespace, while `import { __ } from '…'` reads the
    // named export off the same object. Binding the default directly would
    // serve the first and break the second.
    //
    // Each namespace is re-wrapped by esm() below, because a bundler's CJS
    // interop helper decides how to read a global by looking for `__esModule`.
    // A real module namespace does not carry that flag, so the helper assumes
    // CommonJS and hands back the whole namespace as the default export — the
    // page then renders an object as a component and React throws #130.
    Object.keys(CONTRACT).forEach((specifier, index) => {
        const local = `_m${index}`;
        imports.push(`import * as ${local} from ${JSON.stringify(specifier)};`);
        bindings.set(specifier, `esm(${local})`);
    });

    const tree = nest(bindings);

    return `${[
        '// GENERATED by @openmes/module — do not edit.',
        '// Regenerated on every Vite build from packages/module/contract.js.',
        '',
        ...imports,
        '',
        '// Copy each namespace into a plain object carrying the __esModule flag,',
        '// so a module bundle\'s interop helper treats it as an ES module and reads',
        '// `.default` for default imports instead of handing back the namespace.',
        'const esm = (ns) => ({ __esModule: true, ...ns });',
        '',
        `window.${RUNTIME_GLOBAL} = {`,
        `    apiVersion: ${CONTRACT_VERSION},`,
        ...render(tree).slice(1, -1).split('\n'),
        '};',
        '',
        '// Installed modules push their pages in here; the page resolver reads it',
        '// back. Created before any module script runs, and never replaced, so a',
        '// second module cannot wipe the first one\'s registrations.',
        `window.${PAGES_GLOBAL} = window.${PAGES_GLOBAL} ?? {};`,
        '',
    ].join('\n')}`;
}

/**
 * @param {{ entry?: string }} options
 *   entry — where to write the generated runtime, relative to the Vite root.
 *   Must match what the app lists in `laravel({ input: [...] })`.
 */
export function openmesRuntime(options = {}) {
    const entry = options.entry ?? RUNTIME_ENTRY;

    return {
        name: 'openmes-runtime',

        // `config` runs before Vite resolves inputs, so the generated file is on
        // disk by the time the Laravel plugin's entry list is read.
        config(config) {
            const root = config.root ?? process.cwd();
            const target = resolve(root, entry);
            const source = generate();

            // Only write when the content actually changed: this runs on every
            // dev-server config reload, and a touched entry file would restart
            // the watcher in a loop.
            let current = null;
            try {
                current = readFileSync(target, 'utf8');
            } catch {
                // Not there yet — first build in a fresh checkout.
            }

            if (current !== source) {
                mkdirSync(dirname(target), { recursive: true });
                writeFileSync(target, source, 'utf8');
            }
        },
    };
}
