/**
 * Core-side Vite plugin: tells Tailwind where the pages of installed modules
 * are, so the utility classes they use end up in the stylesheet.
 *
 * Pages under modules/<Name>/resources/js/Pages are compiled into the bundle
 * when they are present at build time (see the glob in app.jsx). Their classes
 * were not: Tailwind decides what to scan from .gitignore, and modules/ is
 * listed there because installed modules do not belong to this repository. A
 * module page therefore rendered with every class core happens to use
 * somewhere and none of its own -- an arbitrary value, a breakpoint variant
 * nobody else needed -- which looks like a styling bug in the module.
 *
 * An ignored directory is scanned only when it is named outright. A glob that
 * covers every module at once, or the modules directory itself, is skipped all
 * the same, so the list cannot be written once in app.css; it is generated
 * here, one line per module that ships pages, and imported from there.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';

/** Default location of the generated stylesheet, relative to the Vite root. */
export const MODULE_SOURCES_ENTRY = 'resources/css/modules.generated.css';

const HEADER = [
    '/* GENERATED by @openmes/module — do not edit.',
    '   Regenerated on every Vite build: one @source per installed module that',
    '   ships pages, because Tailwind does not scan modules/ on its own. */',
];

/**
 * The stylesheet's content for the modules found under `modulesDir`.
 *
 * Paths are written relative to the stylesheet, which is how Tailwind reads an
 * @source, and with forward slashes whatever the platform.
 *
 * @param {string} modulesDir absolute path of the modules directory
 * @param {string} cssDir     absolute path of the directory the stylesheet is written to
 */
export function moduleSourcesCss(modulesDir, cssDir) {
    const names = existsSync(modulesDir)
        ? readdirSync(modulesDir, { withFileTypes: true })
            .filter((entry) => entry.isDirectory() || entry.isSymbolicLink())
            .map((entry) => entry.name)
            .filter((name) => existsSync(resolve(modulesDir, name, 'resources/js')))
            .sort()
        : [];

    const sources = names.map((name) => {
        const path = relative(cssDir, resolve(modulesDir, name, 'resources/js')).split(sep).join('/');

        return `@source ${JSON.stringify(path)};`;
    });

    return `${[...HEADER, ...sources].join('\n')}\n`;
}

/**
 * @param {{ entry?: string, modules?: string }} options
 *   entry   — where to write the stylesheet, relative to the Vite root. Must
 *             match the @import in app.css.
 *   modules — the modules directory, relative to the Vite root.
 */
export function openmesModuleSources(options = {}) {
    const entry = options.entry ?? MODULE_SOURCES_ENTRY;
    const modules = options.modules ?? 'modules';

    return {
        name: 'openmes-module-sources',

        // `config` runs before any stylesheet is transformed, so the file
        // app.css imports is on disk by the time Tailwind follows the import.
        config(config) {
            const root = config.root ?? process.cwd();
            const target = resolve(root, entry);
            const source = moduleSourcesCss(resolve(root, modules), dirname(target));

            // Only write when the content changed, for the same reason the
            // runtime entry does: a touched input restarts the watcher.
            let current = null;
            try {
                current = readFileSync(target, 'utf8');
            } catch {
                // Not there yet — first build in a fresh checkout.
            }

            if (current !== source) {
                mkdirSync(dirname(target), { recursive: true });
                writeFileSync(target, source, 'utf8');
            }
        },
    };
}
